---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-app
  labels:
    app: blue-green-app
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: blue-green-app
  type: LoadBalancer
