apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ns
  namespace: argocd
spec:
  project: ovo-teralite-development
  source:
    repoURL: https://github.com/DheerajJoshi/argocd.git
    targetRevision: HEAD
    path: services/app-ns
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app-ns
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
