---
apiVersion: v1
kind: Service
metadata:
  name: canary-app-preview
  labels:
    app: canary-app
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: canary-app
