apiVersion: v1
kind: Secret
metadata:
  name: blue-green-app-secret
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "somesecretgoeshere"
    }
#kubectl create secret generic blue-green-app-secret --from-file .\golang\secrets\secret.json
