---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-app
  labels:
    app: canary-app
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
        - name: canary-app
          image: "alexmt/rollouts-demo:latest"
          # image: "argoproj/rollouts-demo:red"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
          - name: secret-volume
            mountPath: /secrets/
          - name: config-volume
            mountPath: /configs/
      volumes:
      - name: secret-volume
        secret:
          secretName: canary-app-secret
      - name: config-volume
        configMap:
          name: canary-app-config #name of our configmap object
  strategy:
    canary:
       steps:
       - setWeight: 20
       - pause: {}
